In [1]:
import numpy as np

import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

from flask import Flask, jsonify
from sqlalchemy import create_engine

from flask import Response,json

from flask import Flask, jsonify

#from flask_cors import CORS, cross_origin

from flask import Flask, render_template

#################################################
# Database Setup
#################################################
# engine = create_engine("postgres://ucicakrprsnpky:0c02ab311d9965df2f4c471d98f6251dd952fb1263e3962e33a9f4c4ae7fbc78@ec2-54-158-222-248.compute-1.amazonaws.com:5432/dfkdt10l1i8e55")

engine = create_engine("postgres://dijotinjkotssd:db7fb60a896f20e945fe8d81cfa2b4d07537011ed1ffec0d02b3d9407bd982a6@ec2-3-214-3-162.compute-1.amazonaws.com:5432/decuhc9k7edl3j")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save reference to the table

results = engine.execute("select * from breweries").fetchall()

In [4]:
import pandas as pd
df = pd.DataFrame(results)

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,10-56-brewing-company-knox,10-56 Brewing Company,micro,400 Brown Cir,Not Available,Not Available,Knox,Indiana,Not Available,46534,...,2018-08-24 00:32:25,United States,-86.627954,41.289715,Not Available,Midwest,Indiana,IN,Midwest,East North Central
1,10-barrel-brewing-co-bend-pub-bend,10 Barrel Brewing Co - Bend Pub,large,62950 NE 18th St,Not Available,Not Available,Bend,Oregon,Not Available,97701,...,2018-08-24 15:45:44,United States,-121.28095359999999,44.0912109,Not Available,Oregon,Oregon,OR,West,Pacific
2,10-barrel-brewing-co-boise-boise,10 Barrel Brewing Co - Boise,large,826 W Bannock St,Not Available,Not Available,Boise,Idaho,Not Available,83702-5857,...,2020-10-11 17:00:13,United States,-116.202929,43.618516,Not Available,Idaho,Idaho,ID,West,Mountain
3,10-barrel-brewing-co-denver-denver,10 Barrel Brewing Co - Denver,large,2620 Walnut St,Not Available,Not Available,Denver,Colorado,Not Available,80205-2231,...,2018-08-24 00:05:11,United States,-104.9853655,39.7592508,Not Available,Colorado,Colorado,CO,West,Mountain
4,10-barrel-brewing-co-portland,10 Barrel Brewing Co,large,1411 NW Flanders St,Not Available,Not Available,Portland,Oregon,Not Available,97209-2620,...,2018-08-24 15:45:43,United States,-122.68550559999998,45.5259786,Not Available,Oregon,Oregon,OR,West,Pacific

In [6]:
columns = engine.execute("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'breweries'").fetchall()

In [12]:
new_columns = []
for i in columns:
    new_columns.append(i[0])

In [13]:
new_columns

['obdb_id',
 'name',
 'brewery_type',
 'street',
 'address_2',
 'address_3',
 'city',
 'state',
 'county_province',
 'postal_code',
 'website_url',
 'phone',
 'created_at',
 'updated_at',
 'country',
 'longitude',
 'latitude',
 'tags',
 'region_delete',
 'state2',
 'state_code',
 'region',
 'division']

In [14]:
df.columns = new_columns

In [15]:
df.head()

,obdb_id,name,brewery_type,street,address_2,address_3,city,state,county_province,postal_code,...,updated_at,country,longitude,latitude,tags,region_delete,state2,state_code,region,division
0,10-56-brewing-company-knox,10-56 Brewing Company,micro,400 Brown Cir,Not Available,Not Available,Knox,Indiana,Not Available,46534,...,2018-08-24 00:32:25,United States,-86.627954,41.289715,Not Available,Midwest,Indiana,IN,Midwest,East North Central
1,10-barrel-brewing-co-bend-pub-bend,10 Barrel Brewing Co - Bend Pub,large,62950 NE 18th St,Not Available,Not Available,Bend,Oregon,Not Available,97701,...,2018-08-24 15:45:44,United States,-121.28095359999999,44.0912109,Not Available,Oregon,Oregon,OR,West,Pacific
2,10-barrel-brewing-co-boise-boise,10 Barrel Brewing Co - Boise,large,826 W Bannock St,Not Available,Not Available,Boise,Idaho,Not Available,83702-5857,...,2020-10-11 17:00:13,United States,-116.202929,43.618516,Not Available,Idaho,Idaho,ID,West,Mountain
3,10-barrel-brewing-co-denver-denver,10 Barrel Brewing Co - Denver,large,2620 Walnut St,Not Available,Not Available,Denver,Colorado,Not Available,80205-2231,...,2018-08-24 00:05:11,United States,-104.9853655,39.7592508,Not Available,Colorado,Colorado,CO,West,Mountain
4,10-barrel-brewing-co-portland,10 Barrel Brewing Co,large,1411 NW Flanders St,Not Available,Not Available,Portland,Oregon,Not Available,97209-2620,...,2018-08-24 15:45:43,United States,-122.68550559999998,45.5259786,Not Available,Oregon,Oregon,OR,West,Pacific

In [27]:
df["region"].value_counts().to_dict()

{'West': 1768, 'Midwest': 1292, 'South': 1102, 'Northeast': 773}